# Generated by Django 4.2.1 on 2023-05-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('tipoPersona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appi.tipo_persona')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_produto', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appi.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('numero_ventas', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_de_factura', models.BigIntegerField()),
                ('estado_factura', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appi.persona')),
                ('producto1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appi.producto')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appi.persona')),
            ],
        ),
    ]
